name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  claude:
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Run Claude Code Action
        uses: grll/claude-code-action@beta
        with:
          use_oauth: true
          claude_oauth_refresh_token: ${{ secrets.CLAUDE_OAUTH_REFRESH_TOKEN }}
          timeout_minutes: "30"